VECTOR_DB_NAME: "faiss_index"
CREATE_NEW_INDEX: FALSE
PDF_FILES: "./pdf_files/"
LLM_MODEL: "gemini-1.5-flash"
EMBEDDING_MODEL: "models/embedding-001"
MODE_SELECTOR: 'Human' #LLM
MODE: 'qa' # summary, qa, general